version: '2'
services:
    wilkestechdemo-app:
        image: wilkestechdemo
        external_links:
            - wilkestechdemo-postgresql:postgresql
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/wilkestechDemo
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    wilkestechdemo-postgresql:
        extends:
            file: postgresql.yml
            service: wilkestechdemo-postgresql
