CREATE ROLE app WITH NOSUPERUSER NOINHERIT NOCREATEDB NOCREATEROLE NOREPLICATION;

CREATE ROLE app_user WITH LOGIN PASSWORd :dbAppUserPwd NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION IN ROLE app;

GRANT ALL ON DATABASE :dbName to :dbAdmin;
GRANT CONNECT, TEMPORARY ON DATABASE :dbName TO app;
REVOKE ALL ON DATABASE :dbName FROM public;

CREATE SCHEMA :dbSchema AUTHORIZATION :dbAdmin;

GRANT USAGE ON SCHEMA :dbSchema TO app;

ALTER DEFAULT PRIVILEGES IN SCHEMA :dbSchema
	GRANT INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER ON TABLES TO app;

CREATE SCHEMA :liquibaseSchema AUTHORIZATION :dbAdmin;